---
title: "Negation in Reference"
author: "Alex Tunkel and Dan Yurovsky"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: false
    number_sections: false
    theme: lumen
    toc_float: false
    code_folding: hide
---

```{r load-libraries, message=FALSE, warning=FALSE, show = F}
library(forcats)
library(knitr)
library(tidyboot)
library(stringr)
library(here)
library(ggthemes)
library(lme4)
library(lmerTest)
library(broom)
library(broom.mixed)
library(tidyverse)
library(glue)
library(ggthemes)

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = TRUE, tidy = FALSE)


theme_set(theme_few(base_size = 16))
```

```{r load_data, eval = F}
#data <- read_csv(here("data/pilot3.csv")) 
#data <- read_csv(here("data/experiment2.csv")) 
data <- read_csv(here("data/experiment3.csv")) 
```

```{r munge_data, eval = F}
false_alarms <- c("nothing", "not sure", "something that you smell not eat",
                  "Another form of art")

test_data <- data %>%
  filter(type != "practice") %>%
  arrange(id, trial) %>%
  group_by(id, target) %>%
  mutate(occurrence = 1:n()) %>%
  group_by(id) %>%
  mutate(switch = lag(occurrence == 3),
         switch = if_else(is.na(switch), FALSE, switch),
         switch = factor(switch, levels = c(FALSE, TRUE), 
                         labels = c("standard", "switch")),
         response = if_else(is.na(response), "", response)) %>%
  ungroup() %>%
  mutate(negation = str_detect(response, "not"),
         negation = if_else(response %in% false_alarms,
                            FALSE, negation))

write_csv(test_data, here("data/test_data_e3.csv"))
```

read hand-coded data
```{r load_coded_data, eval = T}
test_data_e1 <- read_csv(here("data/test_data_coded.csv")) %>%
  mutate(experiment = "1")
test_data_e2 <- read_csv(here("data/test_data_e2_coded.csv")) %>%
  mutate(experiment = "2")
test_data_e3 <- read_csv(here("data/test_data_e3.csv")) %>%
  mutate(experiment = "3")

all_data <- bind_rows(test_data_e1, test_data_e2, test_data_e3) %>%
  mutate(id = as.character(glue("{experiment}_{id}")))
```

```{r summarise_data}
mean_data <- all_data %>% 
  group_by(experiment, type, switch, id) %>%
  summarise(negation = mean(negation)) %>%
  tidyboot_mean(negation) %>%
  mutate(empirical_stat = empirical_stat)
```

```{r plot_negation}
ggplot(mean_data, aes(x = switch, y = empirical_stat, color = experiment)) + 
  facet_wrap(~ type) +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(.5)) + 
  scale_color_ptol() + 
  labs(y = "negation probability", x = "") + 
  theme(legend.position = c(.2,.6), aspect.ratio = 1)
```

```{r models, eval = FALSE}
model <- glmer(negation ~  switch * experiment + (1 |id) + (1|target), 
            family = "binomial", data = all_data %>% filter(type == "unknown"))

model <- glmer(negation ~  switch * experiment + (1 |id) + (1|target), 
            family = "binomial", data = all_data %>% filter(type == "known"))

# 
# model <- stan_glmer(negation ~  type *switch * experiment + (1 |id) + (1|target), 
#             family = "binomial", data = all_data %>% mutate(negation = as.numeric(negation)))

tidy(model) %>%
  filter(effect == "fixed") %>%
  select(-group, - std.error) %>%
  kable()
```