---
title: "Preregistered analyses for E1"
author: "Alex Tunkel and Dan Yurovsky"
date: '`r Sys.Date()`'
output: 
  html_document:
  toc: false
number_sections: false
theme: lumen
toc_float: false
code_folding: hide
---
  
```{r load-libraries, message=FALSE, warning=FALSE, show = F}
library(forcats)
library(knitr)
library(tidyboot)
library(stringr)
library(here)
library(lme4)
library(lmerTest)
library(broom)
library(broom.mixed)
library(ggthemes)
library(tidyverse)


opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = TRUE, tidy = FALSE)


theme_set(theme_few(base_size = 12))
```

Read hand-coded data
```{r load_coded_data, eval = FALSE}
pre_processed_data <- read_csv(here("data/pilots/combined/pre_processed_data.csv"))

manually_coded_data <- read_csv(here("data/pilots/combined/manually_coded_data.csv"))

coded_data <- pre_processed_data %>%
  select(-negation) %>%
  left_join(manually_coded_data, by = c("mixed_repeated", "order", "id",
                                        "trial", "response"))

excluded_ps <- coded_data %>%
  filter(is.na(negation)) %>%
  distinct(id) %>%
  pull()

write_csv(coded_data, here("data/pilots/combined/coded_data.csv"))
```

```{r read_coded_data, message = FALSE, warning= FALSE}
coded_data <- read_csv(here("data/pilots/combined/coded_data.csv")) %>%
  filter(!is.na(negation)) %>%
  mutate(block = if_else(trial >= 11, 2, 1),
         block_type =  case_when(
           order == "mixed first" & block == 2 ~ "all unknown",
           order == "unknown first" & block == 1 ~ "all unknown",
           T ~ "mixed"),
         target_type = factor(target_type, levels = c("known", "unknown"), 
                           labels = c("known target", "unknown target")),
         distractor_type = factor(distractor_type, 
                                  levels = c("known", "unknown"), 
                           labels = c("known distractor", 
                                      "unknown distractor")))
         
         # ,
         # block_type = factor(block_type, 
         #                     levels = c("unknown first", "mixed first")))

unknown_data <- filter(coded_data, target_type == "unknown target")
```

```{r}
coded_data %>%
  filter(target_type == "unknown target", distractor_type == "known distractor",
         switch == "switch") %>%
  group_by(order, mixed_repeated) %>%
  count()
```

```{r summarise_data}
mean_data <- coded_data %>% 
  group_by(block_type, order, target_type, distractor_type, switch, id) %>%
  summarise(negation = mean(negation, na.rm = T)) %>%
  tidyboot_mean(negation)
```

```{r plot_negation}
ggplot(mean_data,
       aes(x = switch, y = empirical_mean, color = target_type, 
           shape = distractor_type)) + 
  facet_grid(order ~ block_type) +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(.5)) + 
  scale_color_ptol() + 
  labs(y = "negation probability", x = "") + 
  theme(legend.position = "bottom")
```

Predicted three way interaction between trial type, order, and distractor type 
```{r plot_unknown_negation} 
ggplot(mean_data %>% filter(target_type == "unknown target"),
       aes(x = switch, y = empirical_mean, color = distractor_type, 
           shape = order)) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(.5)) + 
  scale_color_ptol() + 
  labs(y = "negation probability", x = "") + 
  theme(legend.position = "bottom")
```


```{r model}
simplest_model <- glmer(negation ~ switch * distractor_type * order + 
                          (1 |  id), family = "binomial", 
                        data = unknown_data) %>%
  tidy() %>%
  filter(effect == "fixed") %>%
  select(-group, -effect)
```

```{r models, eval = FALSE}
# Will try maximal model first, and then subsequent models sequentially 
# until a model converges withou any error messages or warnings
maximal_model <- glmer(negation ~ switch * distractor_type * order + 
                         (switch * distractor_type | id) + (1 | target) + 
                         (1 | distractor),  family = "binomial", 
                       data = unknown_data) %>%
  tidy() %>%
  filter(effect == "fixed") %>%
  select(-group, -effect)

no_interaction_slope_model <- glmer(negation ~ switch * distractor_type * 
                                      order + (switch + distractor_type | id) + 
                                      (1 | target) + (1 | distractor), 
                                    family = "binomial", 
                                    data = unknown_data) %>%
  tidy() %>%
  filter(effect == "fixed") %>%
  select(-group, -effect)

no_slope_model <- glmer(negation ~ switch * distractor_type * order + 
                          (1 | id) + (1 | target) + (1 | distractor), 
                        family = "binomial", 
                        data = unknown_data) %>%
  tidy() %>%
  filter(effect == "fixed") %>%
  select(-group, -effect)

no_distractor_model <- glmer(negation ~ switch * distractor_type * order + 
                               (1 |  id) + (1 | target), family = "binomial", 
                             data = unknown_data) %>%
  tidy() %>%
  filter(effect == "fixed") %>%
  select(-group, -effect)

no_target_model <- glmer(negation ~ switch * distractor_type * order + 
                          (1 |  id) , family = "binomial", 
                        data = unknown_data) %>%
  tidy() %>%
  filter(effect == "fixed") %>%
  select(-group, -effect)
```
